//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaFilesSharing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentID { get; set; }
        public int FileID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string CommentContent { get; set; }
        public string IP { get; set; }
        public System.DateTime Date { get; set; }
        public string Poster { get; set; }
    
        public virtual File File { get; set; }
    }
}
